export { default as Home } from './Home'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Users } from './Users'
export { default as UserDetail } from './UserDetail'
export { default as Page404 } from './Page404'
